---
language:
  - ruby
  - node_js
rvm:
  - 2.2.2
node_js:
  - stable
  - iojs
  - iojs-v2
cache:
  bundler: true
  directories:
    - bower_components
    - node_modules
sudo: false

before_script:
  - npm install

before_install:
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis
