---
language: [ ruby, node_js ]
rvm: [ 2.2.2 ]
node_js: [ iojs ]
cache:
  bundler: true
  directories:
    - bower_components
sudo: false

before_script:
  - npm install -g bower
  - bower install

before_install:
  - 'echo ''gem: --no-document'' > ~/.gemrc'

script: bundle exec rake travis
